# Generated by Django 2.0.4 on 2018-05-01 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(8)])),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('created_at', models.DateTimeField(editable=False)),
                ('viewed_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
        ),
    ]
