# Generated by Django 2.0.4 on 2018-05-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180501_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='viewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
