# Generated by Django 2.0.4 on 2018-05-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180503_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='viewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
